export type Profile = {
  id: string;
  created_at: string;
  updated_at: string;
  username: string | undefined;
  avatar_url: string | undefined;
  plan: string | undefined;
  contact_madd: string | undefined;
  year_of_birth: string | undefined;
  zip: string | undefined;
  job: string | undefined;
  facebook: string | undefined;
  twitter: string | undefined;
  homepage: string | undefined;
  blog: string | undefined;
  gender: string | undefined;
};
export type EditedProfile = {
  username: string | undefined;
  avatar_url: string | undefined;
  contact_madd: string | undefined;
  year_of_birth: string | undefined;
  zip: string | undefined;
  job: string | undefined;
  facebook: string | undefined;
  twitter: string | undefined;
  homepage: string | undefined;
  blog: string | undefined;
  gender: string | undefined;
};
export type Post = {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string | undefined;
  title1: string | undefined;
  title2: string | undefined;
  stitle: string | undefined;
  expire: Date | null;
  guide: string | undefined;
  cat: string | undefined;
  image_url: string | undefined;
  started_at: Date | null;
  post_flg: string | undefined;
  stoped_at: string | undefined;
  username: string | undefined;
  avatar_url: string | undefined;
};
export type Posts = { posts: Post[] };
export type EditedPost = {
  id: string | undefined;
  user_id: string | undefined;
  title1: string | undefined;
  title2: string | undefined;
  stitle: string | undefined;
  expire: Date | null;
  guide: string | undefined;
  cat: string | undefined;
  image_url: string | undefined;
  started_at: Date | null;
  post_flg: string | undefined;
  username: string | undefined;
  avatar_url: string | undefined;
};
export type Comment = {
  id: string;
  suki: string;
  user_id: string;
  created_at: string;
  updated_at: string;
  username: string;
  image_url: string | undefined;
  text: string | undefined;
  delf: string;
};
export type Reply = {
  id: string;
  created_at: string;
  cuser_id: string;
  ruser_id: string;
  updated_at: string;
  username: string;
  image_url: string | undefined;
  comment: string | undefined;
  delf: string;
};
