import type { NextPage } from "next";
import Head from "next/head";

import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";

import { Navigation, Pagination, Scrollbar, A11y, Autoplay } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const slidetexts = ["Slide 1", "Slide 2", "Slide 3", "Slide 4", "Slide 5"];

  return (
    <>
      <Head>
        <title>Use Swiper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container spacing={0} className="margin-top60">
          <Grid item xs={12} alignItems="center" className="padding20">
            <Typography variant="h3">Welcome to unremoted.com</Typography>
          </Grid>
          <Grid item xs={12} alignItems="center" className="padding20">
            <Swiper
              modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
              spaceBetween={50}
              slidesPerView={1}
              navigation={true}
              pagination={{ clickable: true }}
              // scrollbar={{ draggable: true }}
              onSwiper={(swiper) => console.log(swiper)}
              loop={true}
              speed={500}
            >
              {slidetexts.map((slidetext: string, index: number) => {
                return (
                  <SwiperSlide key={`${index}`}>
                    <Typography
                      align="center"
                      variant="h5"
                      className={styles.textblackP301}
                    >
                      {slidetext}
                    </Typography>
                  </SwiperSlide>
                );
              })}
            </Swiper>
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://unremoted.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by unremote.com
        </a>
      </footer>
    </>
  );
};

export default Home;
