import type { NextPage } from "next";
import Head from "next/head";

import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container spacing={0} className="margin-top60">
          <Grid item xs={12} alignItems="center" className="padding20">
            <Typography variant="h3">Welcome to unremoted.com</Typography>
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://unremoted.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by unremote.com
        </a>
      </footer>
    </div>
  );
};

export default Home;
